config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get 'about', to: 'pages#about'

  resources :songs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :body, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def about
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      flash[:notice] = "Song was successfully created"
      redirect_to song_path(@song)
    else
      render 'new'
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def index
    @songs = Song.all
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(article_params)
      flash[:notice] = "Song was updated"
      redirect_to article_path(@song)
    else
      flash[:notice] = "Song was not updated"
      render 'edit'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:notice] = 'Song was deleted'
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:title, :club)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nrlss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Blog</h1>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>
<%= link_to 'About', about_path %>

app/views/songs/_form.html.erb
<% if @song.errors.any? %>
  <h2>The following errors prevented the article from saving:</h2>
  <ul>
    <% @song.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @song do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :club %><br>
    <%= f.text_field :club %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/songs/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', song_path %>

app/views/songs/index.html.erb
<h1>Listing all articles</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @songs.each do |song| %>
    <tr>
      <td><%= song.title %></td>
      <td><%= song.club %></td>
      <td><%= link_to 'edit', edit_song_path(song) %></td>
      <td><%= link_to 'Show', song_path(song) %></td>
    </tr>
<% end %>
</table>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', song_path %>

app/views/songs/show.html.erb
<h1>Showing Selected Song</h1>
<p>
  Title: <%= @song.title %>
</p>
<p>
  Club: <%= @song.club %>
</p>

<%= link_to 'Back', song_path %>
<%= link_to "Edit", edit_song_path(@song) %>